environment:
  node_pre_gyp_accessKeyId:
    secure: 7DrSVc5eIGtmMcki5H+iRft+Tk3MJTwDBQEUuJHWaQ4=
  node_pre_gyp_secretAccessKey:
    secure: 1amwJJw9fu0j6dXnc5KsAQbSYf7Cjw/dapT6OZWABa6nc52grkKeLQ+DGaOfQz8i
  matrix:
    # Fixed at version until https://github.com/nodejs/node/issues/12244 is resolved by nodejs
    - nodejs_version: 4.8.1
      msvs_toolset: 14
      platform: x64
    - nodejs_version: 4.8.1
      msvs_toolset: 14
      platform: x86
    # Fixed at version until https://github.com/nodejs/node/issues/12244 is resolved by nodejs
    - nodejs_version: 6.10.1
      msvs_toolset: 14
      platform: x64
    - nodejs_version: 6.10.1
      msvs_toolset: 14
      platform: x86

os: Visual Studio 2015

clone_depth: 20

install:
  - scripts\build-appveyor.bat

artifacts:
  - path: build\stage\**\*.gz
    name: package

build: off
test: off
deploy: off
